<?php
$dosen=[
    '1. Dany Indra Gunawan <br>' => [
        'Nim: 6382942769',
        'Nama: Seni',
        'Umur: 17 Tahun',
        'Email: Seni@gmail.com <br>',
        'Nim: 4594290156',
        'Nama: Kayla',
        'Umur: 17 Tahun',
        'Email: kayla@gmail.com <br>',
        'Nim: 8064738513',
        'Nama: Risma',
        'Umur: 18 Tahun',
        'Email: Risma@gmail.com <br>',
        'Nim: 9534276054',
        'Nama: Adzura',
        'Umur: 18 Tahun',
        'Email: Zura@gmail.com <br>',
        'Nim: 0657323156',
        'Nama: Abel',
        'Umur: 18 Tahun',
        'Email: Abel@gmail.com <br>'
    ],
    '2. Muhammad Sabar <br>' => [
        'Nim: 8536723975',
        'Nama: Lira',
        'Umur: 18 Tahun',
        'Email: Lira@gmail.com <br>',
        'Nim: 7438942715',
        'Nama: Meylani',
        'Umur: 18 Tahun',
        'Email: Mey@gmail.com <br>',
        'Nim: 0858463721',
        'Nama: Maudy',
        'Umur: 18 Tahun',
        'Email: Maudy@gmail.com <br>',
        'Nim: 0678435627',
        'Nama: Syifa',
        'Umur: 18 Tahun',
        'Email: Syifa@gmail.com <br>',
        'Nim: 865352891',
        'Nama: Selvi',
        'Umur: 18 Tahun',
        'Email: Selvi@gmail.com <br>'
    ],
    '3. Tarsinah Sumarni <br>' => [
        'Nim: 678392701',
        'Nama: Rifa',
        'Umur: 17 Tahun',
        'Email: Rifa@gmail.com <br>',
        'Nim: 046561886',
        'Nama: Sel',
        'Umur: 17 Tahun',
        'Email: Sel@gmail.com <br>',
        'Nim: 975380064',
        'Nama: Marni',
        'Umur: 20 Tahun',
        'Email: Marni@gmail.com <br>',
        'Nim: 584564675',
        'Nama: Ica',
        'Umur: 17 Tahun',
        'Email: Ica@gmail.com <br>',
        'Nim: 7664859697',
        'Nama: Memey',
        'Umur: 16 Tahun',
        'Email: Memey@gmail.com <br>'
    ],
    '4. Saepudin <br>' => [
        'Nim: 64380865',
        'Nama: Siti',
        'Umur: 17 Tahun',
        'Email: Siti@gmail.com <br>',
        'Nim: 0478957638',
        'Nama: Santi',
        'Umur: 17 Tahun',
        'Email: Santi@gmail.com <br>',
        'Nim: 688647388',
        'Nama: Imoy',
        'Umur: 18 Tahun',
        'Email: Imoy@gmail.com <br>',
        'Nim: 74902686',
        'Nama: Risa',
        'Umur: 18 Tahun',
        'Email: Risa@gmail.com <br>',
        'Nim: 587427986',
        'Nama: Nita',
        'Umur: 19 Tahun',
        'Email: Nita@gmail.com <br>'
    ],
];

echo json_encode($dosen);
?>